---
title: Chess is sometimes more entertaining than Cricket
author: Kurian Benoy
categories: [chess, Life]
date: 2023-07-03
date-format: full
---

The statement in my headline is an extremely polarizing one especially as an Indian.
Yet folks, I didn't say always I just said sometimes and as someone who watched the
game against Triveni Continental Kings vs upGrad Mumba Masters finals in Global Chess
League.

First of all, I am terrible at chess and I don't enjoy playing chess much. I like to
watch chess more and follow some of the interesting personalities in chess world.

The situation in the watch can be well explained with this youtube video. So do watch
it if you want a recap. Yet let me describe the match for you:

This was a team tournament with 6 players each fighting for their team. Their was the
icons board, followed by two mens board, two female players board and finally a prodigy
board. The format was first two chess rapid games of 15 minutes time for each players.
The first rapid game playing with white was won by Triveni Continental Kings and the 
second rapid game was won by upGrad Mumba Masters playing with White.
This forced to go into a blitz match of 5 minutes time for each team. This time 
Triveni Continental Kings was white but they lost. In a must win game for Triveni Continental Kings
with black, they managed to do the impossible in a must win sitation.

This forced into a player vs player tie breaker. Three players played and each of them tied.
The last match was played by GM Jonas Bjerre from Denmark and GM  Javokhir Sindarov. The
crazy thing was in all the four matches played in the final,  Javokhir Sindarov had won it.
The match ended with Triveni Continental Kings winning when Jonas defeated Sindarov with
 a checkmate.

{{< video https://youtu.be/Ipz5yp3HzL4 >}}

The tournament was well-organized and it was nice to see growing popular and popular
as someone who has been following it for a few years. The event winners Triveni Continental Kings
won the grand prize of $500,000 which had an Indian company Tech Mahindra sponsoring it.
It's been good to see Indian companies like Tech Mahindra, Tata Steel sponsoring big events.
India has some talented prodigies like Gukesh, Arjun, Nihal and Pragg. This makes chess
worth watching even more :D.
