project:
  type: website
  output-dir: docs
  preview:
    port: 4900 
website:
  title: "Kurian Benoy"
  twitter-card: true
  favicon: favicon.ico
  open-graph: true
  site-url: https://kurianbenoy.com
  navbar:
    right:
      - text: "Blog"
        href: blog.html
      - text: "Talks"
        href: talks.html
      - text: "TIL"
        href: https://til.kurianbenoy.com/
      - icon: linkedin 
        href: "https://linkedin.com/in/kurianbenoy"
      - icon: twitter
        href: https://twitter.com/kurianbenoy2
      - icon: github
        href: https://github.com/kurianbenoy
      - icon: rss
        href: blog.xml
format:
  html:
    theme:
    - sketchy
    - custom.scss
    css: styles.css
execute:
  freeze: auto
