---
title: "🎤 Talks"
subtitle: Few of my talks and presentations.
comments: false
---


> I like to frequently attend conferences, meetups, devsprints and workshops. I love to give talks as it's an opportunity for me to connect with interesting people from across the world.

::: {layout-ncol=2}
{{< video https://www.youtube.com/embed/g3ysWcvPX5A
    title="OpenAI Whisper and it's amazing power to do finetuning"
>}}

{{< video https://www.youtube.com/embed/ZRtnuGK-e7Y
    title="Demystifying Async & Await in Python & JavaScript"
>}}

{{< video https://www.youtube.com/embed/Ipzf6oQqQpo
    title="Machine Learning Models and Dataset Versioning"
>}}

{{< video https://www.youtube.com/embed/2RzImb5JwMA
    title="At the Eye of Flood - Keralarescue.in"
>}}

{{< video https://www.youtube.com/embed/t_uoI6yOOZg
    title="OpenAI Whisper and it's amazing power to do fine-tuning demonstrated on my mother-tongue"
>}}

{{< video https://www.youtube.com/embed/c69VyJ16Mx4
    title="Malayalam Projects I am working at the moment"
>}}

{{< video https://www.youtube.com/embed/lM0uD56GVrQ
    title="Vistaar paper"
>}}

{{< video https://www.youtube.com/embed/D54awjfoWwQ
    title="OWSM paper"
>}}
:::

These are the list of talks I have delivered:

- Beyond English: Advancing Indic Language AI with Sarvam-M and Bulbul-v2 | [AI Converse Meetup sponsored by Weights and Biases](https://lu.ma/hrmt0kne) | May 31, 2025 | [Slides](https://gamma.app/docs/Beyond-English-Advancing-Indic-Language-AI-with-Sarvam-M-and-Bulb-40zwt6k8bji827k)
- [How I ended up maintaining a python package with 1M+ downloads?](https://www.youtube.com/watch?v=3o2V9BmeoYw&t=372s) | [Kochi FOSS Meetup](https://kochifoss.org/) | April 26, 2025 | [Slides](https://gamma.app/docs/How-I-ended-up-maintaining-building-a-python-package-with-1M-down-o87lazx9yprci5f), [Talk Page](./posts/2025/kochi-foss-april.qmd)

- Why having a great taste is all you need to build great open-source projects | [Code Blossom Online Session](https://www.code-blossom.com/) | June 22, 2024 | [Slides](https://kurianbenoy.com/talks/code_blossom_great_open_source_projects/#/title-slide)

- [Reproducing Whisper-style Training Using an open-source toolkit and publicly available Data](https://youtu.be/D54awjfoWwQ?si=kqUQCAL2dV7d_J4C) | AI4Bharat Paper Reading Group | May 11, 2024 | [Slides](https://kurianbenoy.com/talks/ai4bharat_reproducing_whisper/#/title-slide)

- [Vistaar - Diverse Benchmarks and Training Sets for Indian Language ASR](https://youtu.be/lM0uD56GVrQ?si=IioCJLsnLYTHfnaT) | AI4Bharat Paper Reading Group | April 26, 2024 | [Slides](https://kurianbenoy.com/talks/ai4bharat_paper_reading/#/title-slide)

- LLM 101 Workshop: Beginner session on LLM | [FOSSMEET 2024](https://www.fossmeet.net)- NIT Calicut | March 24, 2024 | [Workshop Materials](https://tiny.cc/llm102), [Kurian Slides](https://kurianbenoy.com/talks/nitc-fossmeet-2024/llm-101.html#/title-slide), [Live Demo Website](https://llm-101-pi.vercel.app) 

- OpenAI Whisper and it's amazing power to do finetuning demonstrated on my Mother tongue | Pycon India, 2023 - Jawaharlal Nehru Technological University, Hyderabad, India. | October 1, 2023 | [Slides](./talks/pyconindia-2023/pyconind.qmd), [Talk Page](./posts/2023/pycon_india2023_talk/index.qmd)

- [OpenAI Whisper and it's amazing power to do fine-tuning demonstrated on my mother-tongue](https://youtu.be/t_uoI6yOOZg) | FOSS Meetup Kochi - KeyValue, Smart Kochi. | June 24, 2023 | [Slides](./talks/foss-united/kochi.qmd),  [Talk Page](./posts/2023/pycon_india2023_talk/) 

- AI with Malayalam Computing | DebUtsav - Govt. Model Engineering College, Thrikkakara. | June 17, 2023 | [Slides](./talks/mec/debutsav.qmd),  [Talk Page](./posts/2023/debutsav_talk/index.qmd) 

- OpenAI Whisper’s amazing power to do fine-tuning demonstrated on Malayalam (Oral Presentation) | Summit 23 - IIIT Kottayam | June 10, 2023 | [Slides](./talks/iiit-kottayam-summit/index.qmd),  [Talk Page](./posts/2023/summit23_iiit/oral.qmd) 

- Vegam Whisper Family of Models and demoing Malayalam Speech to Text (Demo Presentation) | Summit 23 - IIIT Kottayam | June 10, 2023 | [Slides](./talks/iiit-kottayam-summit/demo.qmd), [Talk Page](./posts/2023/summit23_iiit/demo.md) 

- [OpenAI Whisper and it's amazing power to do finetuning](https://youtu.be/g3ysWcvPX5A?si=kRlR6fcuo15IEh5u) | FOSSASIA Summit - Life Long Learning Institue, Singapore | April 15, 2023 | [Slides](./talks/fossasia2023.qmd), [Talk Page](./posts/2023/fossasia2023talk/index.qmd) 

- [Malayalam Projects I am working at the moment](https://youtu.be/c69VyJ16Mx4) | Delft-fastai Meetup | May 28, 2023 | [Slides](./talks/delft-fastai/index.qmd), [Talk page](./posts/2023/delft-fastai-talk/index.qmd) 

- [Demystifying Async & Await in Python & JavaScript](https://youtu.be/ZRtnuGK-e7Y) | Pycon India | September 19, 2021 | [Slides](https://speakerdeck.com/kurianbenoy/demysitfying-async-and-await-in-python-and-javascript)

- [Machine Learning Models and Dataset Versioning](https://www.youtube.com/watch?v=Ipzf6oQqQpo) | Pycon India - Chennai Trade Center ,Chennai | October 13, 2019 | [Slides](https://speakerdeck.com/kurianbenoy/ml-models-and-dataset-versioning)

- [Project Showcase - ToonIt project](https://youtu.be/qi1cVGTa3sg?t=9641) | Tensorflow UserGroup India Summit 2020 | September 6, 2020 | [Slides](https://speakerdeck.com/kurianbenoy/tensorflow-user-groups-tfug-india-summit)

- [At the Eye of Flood - Keralarescue.in](https://www.youtube.com/watch?v=2RzImb5JwMA) | FOSSASIA Summit - Life Long Learning Institue, Singapore | March 17, 2019 | [Slides](https://speakerdeck.com/kurianbenoy/at-the-eye-of-flood-keralarescue-dot-in)

- [Pitfalls, Glamour and Valuable advice from an AI/ML Expert](https://podcasts.google.com/?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy80NmRkNzdhMC9wb2RjYXN0L3Jzcw&ep=14) | Innovate At MEC Podcast | 7th January, 2021

- Introduction to Datascience and ML (Human Library)| [Kochi FOSS](https://indiafoss.net/Kochi/2022) | Govt. Model Engineering College | October 15, 2022

- Expert Interaction Sessions | St Peters VHSS, Kolenchery, Kolenchery | 2022 | [Joy of Programming Slides](https://speakerdeck.com/kurianbenoy/joy-of-programming), [ML and Learning CS in real-world](https://speakerdeck.com/kurianbenoy/expert-interaction-on-ml)

- Tinkerhub Learning class- Python for beginners | February-March, 2020

- Introduction to Django2 | Kochi Python Meetiup | July 07, 2018 | [Slides](https://speakerdeck.com/kurianbenoy/the-hitchikers-guide-to-django2)

<!-- | # | Topic | Venue | Event | Date | Slides | Links |
| :-- |:---- |:----| :---- | :---- | :--- | :---|
|1. | Demystifying Async & Await in Python & JavaScript | Online using Hoppin | Pycon India | September 19, 2021 | [Slide Link](https://speakerdeck.com/kurianbenoy/demysitfying-async-and-await-in-python-and-javascript)| [Talk Video](https://youtu.be/ZRtnuGK-e7Y) |
|2. | Machine Learning Models and Dataset Versioning | Chennai Trade Center ,Chennai, India | Pycon India | October 13, 2019 | [Slide Link](https://speakerdeck.com/kurianbenoy/ml-models-and-dataset-versioning)| [Talk Video](https://www.youtube.com/watch?v=Ipzf6oQqQpo) |
|3. | At the Eye of Flood - Keralarescue.in | Life Long Learning Institue, Singapore  | FOSSASIA Summit  | March 17, 2019 |  [Slide Link](https://speakerdeck.com/kurianbenoy/at-the-eye-of-flood-keralarescue-dot-in)  | [Talk Video](https://www.youtube.com/watch?v=2RzImb5JwMA) |
|4. | Project Showcase - ToonIt project | Online | Tensorflow UserGroup India Summit 2020| September 6, 2020 |  [Slide Link](https://speakerdeck.com/kurianbenoy/tensorflow-user-groups-tfug-india-summit) | [Talk Video](https://youtu.be/qi1cVGTa3sg?t=9618) |
|5. | Tinkerhub Learning class- Python for beginners | Online | Learn From Home Program |  February-March, 2020 | N/A |[Talk Video](https://www.youtube.com/watch?v=2RzImb5JwMA) |
|6. | Introduction to Django2 | Kochi |  Kochi Python Meetiup | July 07, 2018 | [Slides](https://speakerdeck.com/kurianbenoy/the-hitchikers-guide-to-django2) | N/A |
|7. | Pitfalls, Glamour and Valuable advice from an AI/ML Expert | Online |  Innovate At MEC Podcast | 7th January, 2021 | N/A |  [Podcast Link](https://podcasts.google.com/?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy80NmRkNzdhMC9wb2RjYXN0L3Jzcw&ep=14) |
|8. | Human Library - Introduction to Datascience and ML | Govt. Model Engineering College | Kochi Foss | October 15, 2022 | N/A | [link](https://indiafoss.net/Kochi/2022) | -->
