---
title: AI with Malayalam Computing!
subtitle: DebUtsav 2023, Govt. Model Engineering College, Thrikkakara.
date: 2023-06-17
date-format: full
comments: false
draft: true
---

## Links to talk

- [Slides](../../../talks/mec/debutsav.qmd)

- Scheduled Time: Saturday, June 17, 2023, 2:45 PM IST - 3:45 PM IST

## Questions received

1. Why is Malayalam more complex than other languages like Malayalam, I understand your method of comparing TTR. Yet isn't the method of comparing TTR with other languages absurd as the data used for comparission in the dataset might not have all words of a particular language?
2. Do you think whether just a privileged few people can do Machine Learning?
3. What do you think about Mojo, will it help in reducing the problem of few privileged people doing ML?
4. How much resources is required to fine tune Whisper models?
5. How much did it cost for you to do benchmarking in Malayalam?
6. Does it really cost $30 to buy a biriyani for a family in Singapore? (Sorry that during the talk, I mentioned it cost $30 to buy one biriyani in Singapore. This analogy was done inorder to compare cost of benchmarking models for Malayalam. In Singapore the maximum I had to spent for a dinner was 32 SGD during my recent visit.)
7. I absoluted loved `whisper.cpp` because it's able to provide timestamps as well, is it possible to implement timestamps in Malayalam as well?
8. What are your thoughts on LLM finetuning?


## Thanks to

All the folks who asked questions and made the session interactive, a big thank you.
As a speaker, it was the first time I was satisfied with myself for making the session
interactive as this session was right after having a delicious lunch of biriyani.
Also a special thanks to the volunteer who distributed the chocolotes to folks
who answered my quiz questions.
