---
title: LLM 101 Workshop
author: Kurian Benoy
subtitle: Talk Page for my talk @ FOSSMEET 2024, NIT Calicut.
date: 2024-02-24
date-format: full
categories: [conference, Audio, Deep learning, "Talk Page", LLM]
lang: en
draft: true
---

The LLM 101 workshop was something of a labor of love. Instead of submitting CFTs, even though I wanted to apply for CFTs, I was lucky to be contacted by Madhav, CM Madhav Pradubbu, and some other people. Madhav actually contacted me via LinkedIn. They wanted to have an LLM section, and I was definitely interested in conducting that. Because of that, I immediately said yes to Madhav's request. I was very excited about the workshop. I was thinking about playing in JNI space and all those things. So, I also wanted to build something in the workshop. Literally, I got busy building in the subtitle. A lot of things happened in my personal life as well. Madhav wanted to have some teammates because doing the workshop alone is not a very good idea. I thought of Nidin Sabu, one of my batchmates. Nidin Sabu, the vice chairman of Force MEC, saw my details on the top page. He contacted me and was excited to be part of it. I asked Nidin if he would be willing to help me in my workshop, and he said yes. So, that's how I roped in Nidin. When we were building Indic Subtitler, Aldrin was also part of my team. Aldrin was also very excited to come to Force MEC. I made him a speaker. Thinking back, I think having three speakers in the workshop was a very good idea. I will say we were a bit prepared just a week before. We finalized the structure and started working on the content. Unfortunately, our week was busy, and we literally prepared on the last day. The workshop was structured with introduction sections to generative AI, cool tools, and a cool demo planned to be shown to the users. I was supposed to do a cool demo. Later, there would be an introduction to OpenAI, all AMA's, theory stuff like transformers, and prompting techniques. We were even planning for a two-hour hackathon session. Unfortunately, even though we had six hours, we started late due to syncing issues. We didn't have enough time, we might have got close to six hours. We had to skip the hackathons due to time constraints. Initially, I started with the introduction to generative AI and applications, then proceeded with the cool demo. Aldrin introduced OpenAI APIs and Streamlet. Aldrin explained Olam too. By afternoon, most of the workshop audience was from Karnataka and Tamil Nadu. In the afternoon session, many people stopped coming. After Aldrin completed his parts, about half of the audience remained. Then, Nidin conducted his Transformers workshop, showing some prompting techniques. He didn't have much audience, so I requested him to re-record the sessions. I brought a book to gift the winner of the Hackathon, but gave it to a student from IIT Palakkad, as there were few attendees. About the live demo, I had prepared for it but lost energy by then. Aldrin took over and made it interactive. I used Cursor and planned to purchase the Pro version. The live coding was a performance. I knew I might fail, but I enjoyed the challenge. The biggest inspiration was Anand's session during PyCon India. I prepared for the live demo and enjoyed working with giving a live coding session. That's all for this blog post. Thank you.
