---
title: "I got a positive compliment"
author: Kurian Benoy
date: 2023-05-19
draft: true
categories: [myself]
format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
---

[HallaBol Image]

I was supposed to write something before this article. Yet I stopped that and thought about writing an appreciating post to my Gym trainer Rahul. During my work-out session at the GYM, one day my
trainer said Kurian your Calf(which is muscle in our legs) is excellent. Lot of people train very hard to achieve it, yet he said he hasn't seen anyone with excellent Calfs like mine.

I have interacted with people from Singapore, USA, Canada, Germany, Berlin, Vietnam, Nethrlands, Sweden etc. Yet I have always felt Indian's in general are the most insensitive folks as I have faced the following in my life so far:


1. You are become darker and darker in shade ...
2. You are overweight ...
3. Then there are teachers who have made both me and my mother cry whenever I got a bad marks
in exam. 
4. I have faced my only bad experience in technical speaking during a meetup at Kochi.

Now I am in a position where I can pay my bills by working as a Team Lead in a Singapore based company, I have spoken in five international conferences and I am proficent as ML Engineer.

I believe in this famous quote from Servantetes:

> Journey is the inn

The crazy thing is I haven't heard this much from my family, but it has been from some
so called uncles/aunties who call you only during class 10 result times and meet only
during functions. 

I believe life is not one dimensional and being good in just one thing means nothing. Yet
there are some dimensions like Weight loss which is not immediately in our control even when I try
to follow my workout routine atleast 5 times a week.


Despite facing all this I still like living in Kerala, India because:

1. I consider majority of people are nice, and probably only 1% of population is like this way. 
2. On introspecting after my recent trip in Singapore, I personally felt I was more happy just
by walking through the streets in Thiruvanthupuram than even touching Dolphin (which I learned from a kid is National fish of India).

Young folks like Rahul who showed great dedication to his profession and most importantly not doing
body shaming ever in the GYM. In fact I really appreciate his compliment and I am grateful that there are young people  Rahul who are there in my place.

